/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiGymEquipmentGymIdEquipmentIdDelete$Params {
  gymId: string;
  equipmentId: string;
}

export function apiGymEquipmentGymIdEquipmentIdDelete(http: HttpClient, rootUrl: string, params: ApiGymEquipmentGymIdEquipmentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, apiGymEquipmentGymIdEquipmentIdDelete.PATH, 'delete');
  if (params) {
    rb.path('gymId', params.gymId, {});
    rb.path('equipmentId', params.equipmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

apiGymEquipmentGymIdEquipmentIdDelete.PATH = '/api/GymEquipment/{gymId}/{equipmentId}';
