/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeeklySchedule } from '../../models/weekly-schedule';

export interface ApiScheduleMondayGet$Params {
  monday: string;
}

export function apiScheduleMondayGet(http: HttpClient, rootUrl: string, params: ApiScheduleMondayGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WeeklySchedule>>> {
  const rb = new RequestBuilder(rootUrl, apiScheduleMondayGet.PATH, 'get');
  if (params) {
    rb.path('monday', params.monday, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WeeklySchedule>>;
    })
  );
}

apiScheduleMondayGet.PATH = '/api/Schedule/{monday}';
