/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Gym } from '../../models/gym';

export interface ApiGymGet$Params {
}

export function apiGymGet(http: HttpClient, rootUrl: string, params?: ApiGymGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Gym>>> {
  const rb = new RequestBuilder(rootUrl, apiGymGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Gym>>;
    })
  );
}

apiGymGet.PATH = '/api/Gym';
