/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserGet } from '../fn/user/api-user-get';
import { ApiUserGet$Params } from '../fn/user/api-user-get';
import { apiUserIdGet } from '../fn/user/api-user-id-get';
import { ApiUserIdGet$Params } from '../fn/user/api-user-id-get';
import { apiUserPost } from '../fn/user/api-user-post';
import { ApiUserPost$Params } from '../fn/user/api-user-post';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserGet()` */
  static readonly ApiUserGetPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Response(params?: ApiUserGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<User>>> {
    return apiUserGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet(params?: ApiUserGet$Params, context?: HttpContext): Observable<Array<User>> {
    return this.apiUserGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<User>>): Array<User> => r.body)
    );
  }

  /** Path part for operation `apiUserPost()` */
  static readonly ApiUserPostPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiUserPost$Response(params?: ApiUserPost$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return apiUserPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiUserPost(params?: ApiUserPost$Params, context?: HttpContext): Observable<boolean> {
    return this.apiUserPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `apiUserIdGet()` */
  static readonly ApiUserIdGetPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Response(params: ApiUserIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    return apiUserIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet(params: ApiUserIdGet$Params, context?: HttpContext): Observable<User> {
    return this.apiUserIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

}
