/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum MuscleGroup {
  Any = 'Any',
  Arms = 'Arms',
  Back = 'Back',
  Cardio = 'Cardio',
  Chest = 'Chest',
  Core = 'Core',
  Legs = 'Legs',
  Shoulders = 'Shoulders'
}
