/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MuscleGroup } from '../models/muscle-group';
import { WorkoutLog } from '../models/workout-log';
export interface Schedule {
  date?: string;
  id?: string;
  muscleGroupFilter?: Array<MuscleGroup> | null;
  workouts?: Array<WorkoutLog> | null;
}
