/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  email?: string | null;
  firstName?: string | null;
  id?: string | null;
  lastName?: string | null;
  username?: string | null;
}
