/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Schedule } from '../models/schedule';
export interface WeeklySchedule {
  friday?: Schedule;
  monday?: Schedule;
  saturday?: Schedule;
  sunday?: Schedule;
  thursday?: Schedule;
  tuesday?: Schedule;
  wednesday?: Schedule;
}
