/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkoutLog {
  date?: string;
  exerciseId?: string;
  reps?: number;
  scheduleId?: string;
  sets?: number;
  weight?: number;
}
